### ISSUE TITLE
"No alternative textures for this season"

### ISSUE THREAD

**Issue by NickLS1013** [Nordmole/MillnificentCollab#2]
Now it may have been some execution issues or installation issues but I keep getting the error "Building_Mill has no alternative textures for this seasion!" and that is with me installing all the latest versions of the required mods. Would you perhaps know what could be the cause?
![20231028151918_1](https://github.com/Molenfeuer/MillnificentCollab/assets/44042264/4fef660c-a6d7-4356-8f82-6a92a00ae8ae)

**Comment by Molenfeuer** [comment]
Yes :D  You have to build [Millnificent](https://www.nexusmods.com/stardewvalley/mods/16890) first! The Millnificent Mill is a separate Mill. You can find it at the end in Robin's build catalog!

Please tell me if this works for you!

**Comment by NickLS1013** [comment]
That is exactly what was wrong, it's funny what happens when you don't pay attention and read. THANK YOU!!! :3
